Repository moevm/mse1h2025-imitate, pull requests merged in 2025-03, with the labels that each got.

#28 corrected uiux for 1920px, 1200px, 376px
  reports.md
Labels: documentation

#29 23-write-documentation-for-whisperai-and-silerotts
  reports.md
Labels: documentation

#31 24-add-auth-api
  docker-compose.yaml
  mse1h2025_imitate/mse1h2025_imitate/settings.py
  mse1h2025_imitate/mse1h2025_imitate/urls.py
  mse1h2025_imitate/users_manager/serializers.py
  mse1h2025_imitate/users_manager/views.py
  requirements.txt
Labels: backend

#37 added automatic migrations and connecting with the docker network
  docker-compose.yaml
Labels: backend

#40 fixed imports and logic of handling old sessions
  mse1h2025_imitate/users_manager/views.py
Labels: backend

#41 Selenium-reports
  reports.md
Labels: documentation

#45 35-added-tts-service
  Dockerfile
  README.md
  mse1h2025_imitate/backend/models/__init__.py
  mse1h2025_imitate/backend/models/question.py
  mse1h2025_imitate/backend/repositories/__init__.py
  mse1h2025_imitate/backend/repositories/question_repository.py
  mse1h2025_imitate/backend/text_to_speach_service.py
  mse1h2025_imitate/tests/test_question_repository.py
  mse1h2025_imitate/tests/test_tts_service.py
  requirements.txt
Labels: backend

#43 32 tests for authorization and registration
  README.md
  mse1h2025_imitate/tests/test_registration_and_authorization_api.py
  mse1h2025_imitate/tests/test_tts_service.py
  mse1h2025_imitate/users_manager/tests.py
  requirements.txt
Labels: testing

#42 Registration frontend
  README.md
  mse1h2025_imitate/mse1h2025_imitate/settings.py
  mse1h2025_imitate/mse1h2025_imitate/urls.py
  mse1h2025_imitate/static/css/user_manager.css
  mse1h2025_imitate/static/images/account.png
  mse1h2025_imitate/static/images/homepage.png
  mse1h2025_imitate/static/images/logo.png
  mse1h2025_imitate/static/js/script.js
  mse1h2025_imitate/templates/base.html
  mse1h2025_imitate/templates/users_manager/login.html
  mse1h2025_imitate/templates/users_manager/register.html
  mse1h2025_imitate/users_manager/serializers.py
  mse1h2025_imitate/users_manager/views.py
Labels: frontend
