Repository moevm/mse1h2025-imitate, pull requests merged in 2025-04, with the labels that each got.

#70 59 profile
  graduate_imitator/apps/graduation/api/views/users.py
  graduate_imitator/apps/graduation/interfaces/static/css/user.css
  graduate_imitator/apps/graduation/interfaces/static/js/profile.js
  graduate_imitator/apps/graduation/interfaces/templates/user/login.html
  graduate_imitator/apps/graduation/interfaces/templates/user/profile.html
  graduate_imitator/apps/graduation/interfaces/web/views.py
  graduate_imitator/config/urls.py
Labels: frontend, backend

#76 fixed styles usage conflict
  graduate_imitator/apps/graduation/interfaces/static/css/home.css
  graduate_imitator/apps/graduation/interfaces/static/css/user.css
  graduate_imitator/apps/graduation/interfaces/templates/base.html
  graduate_imitator/apps/graduation/interfaces/templates/home/home.html
  graduate_imitator/apps/graduation/interfaces/templates/user/login.html
  graduate_imitator/apps/graduation/interfaces/templates/user/profile.html
  graduate_imitator/apps/graduation/interfaces/templates/user/register.html
Labels: frontend

#73 51 add speech to text service, update requirements.txt
  Dockerfile
  graduate_imitator/apps/graduation/domain/services/speech_to_text_service.py
  graduate_imitator/tests/apps/graduation/test_stt_service.py
  graduate_imitator/tests/resources/test_stt_service/normal_speech.aac
  graduate_imitator/tests/resources/test_stt_service/normal_speech.m4a
  graduate_imitator/tests/resources/test_stt_service/normal_speech.mp3
  graduate_imitator/tests/resources/test_stt_service/normal_speech.ogg
  graduate_imitator/tests/resources/test_stt_service/normal_speech.txt
  graduate_imitator/tests/resources/test_stt_service/normal_speech.wav
  pytest.ini
  requirements.txt
Labels: backend

#77 added questions endpoint
  graduate_imitator/apps/graduation/api/views/protection_api.py
Labels: backend
